In [3]:
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

pd.set_option("display.max_columns", None)

In [4]:
# Load the dataset

df = pd.read_csv("../data/raw/emdat_disasters_1970_2021.csv")

print("Dataset Shape:", df.shape)

Dataset Shape: (14644, 47)

In [5]:
# Create a copy for analysis

analysis_df = df.copy()

print("Working copy created successfully!")

Working copy created successfully!

In [6]:
analysis_df = analysis_df[
    [
        "Year",
        "Country",
        "Region",
        "Continent",
        "Disaster Type",
        "Disaster Subgroup",
        "Start Month",
        "Total Deaths",
        "No Affected",
        "Total Affected",
        "Total Damages ('000 US$)",
        "Dis Mag Value",
        "Latitude",
        "Longitude"
    ]
]

analysis_df.head()

,Year,Country,Region,Continent,Disaster Type,Disaster Subgroup,Start Month,Total Deaths,No Affected,Total Affected,Total Damages ('000 US$),Dis Mag Value,Latitude,Longitude
0,1970,Argentina,South America,Americas,Flood,Hydrological,1.0,36.0,NaN,NaN,25000.0,NaN,NaN,NaN
1,1970,Australia,Australia and New Zealand,Oceania,Storm,Meteorological,1.0,13.0,NaN,NaN,72475.0,NaN,NaN,NaN
2,1970,Benin,Western Africa,Africa,Flood,Hydrological,9.0,NaN,NaN,NaN,200.0,NaN,NaN,NaN
3,1970,Bangladesh,Southern Asia,Asia,Storm,Meteorological,11.0,300000.0,3648000.0,3648000.0,86400.0,NaN,NaN,NaN
4,1970,Bangladesh,Southern Asia,Asia,Storm,Meteorological,4.0,17.0,110.0,110.0,NaN,NaN,NaN,NaN

In [7]:
analysis_df = analysis_df.rename(columns={
    "Disaster Type": "Disaster_Type",
    "Disaster Subgroup": "Disaster_Subgroup",
    "Start Month": "Month",
    "Total Deaths": "Deaths",
    "No Affected": "Affected",
    "Total Affected": "Total_Affected",
    "Total Damages ('000 US$)": "Damage_USD",
    "Dis Mag Value": "Magnitude"
})

analysis_df.head()

,Year,Country,Region,Continent,Disaster_Type,Disaster_Subgroup,Month,Deaths,Affected,Total_Affected,Damage_USD,Magnitude,Latitude,Longitude
0,1970,Argentina,South America,Americas,Flood,Hydrological,1.0,36.0,NaN,NaN,25000.0,NaN,NaN,NaN
1,1970,Australia,Australia and New Zealand,Oceania,Storm,Meteorological,1.0,13.0,NaN,NaN,72475.0,NaN,NaN,NaN
2,1970,Benin,Western Africa,Africa,Flood,Hydrological,9.0,NaN,NaN,NaN,200.0,NaN,NaN,NaN
3,1970,Bangladesh,Southern Asia,Asia,Storm,Meteorological,11.0,300000.0,3648000.0,3648000.0,86400.0,NaN,NaN,NaN
4,1970,Bangladesh,Southern Asia,Asia,Storm,Meteorological,4.0,17.0,110.0,110.0,NaN,NaN,NaN,NaN

In [8]:
analysis_df.isnull().sum()

Year                     0
Country                  0
Region                   0
Continent                0
Disaster_Type            0
Disaster_Subgroup        0
Month                  268
Deaths                4445
Affected              5798
Total_Affected        3603
Damage_USD            9781
Magnitude            10075
Latitude             12313
Longitude            12309
dtype: int64

In [9]:
numeric_columns = [
    "Deaths",
    "Affected",
    "Total_Affected",
    "Damage_USD",
    "Magnitude"
]

analysis_df[numeric_columns] = analysis_df[numeric_columns].fillna(0)

In [10]:
analysis_df = analysis_df.dropna(
    subset=[
        "Disaster_Type",
        "Country",
        "Continent"
    ]
)

In [11]:
print(analysis_df.shape)

analysis_df.info()

(14644, 14)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14644 entries, 0 to 14643
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Year               14644 non-null  int64
 1   Country            14644 non-null  object
 2   Region             14644 non-null  object
 3   Continent          14644 non-null  object
 4   Disaster_Type      14644 non-null  object
 5   Disaster_Subgroup  14644 non-null  object
 6   Month              14376 non-null  float64
 7   Deaths             14644 non-null  float64
 8   Affected           14644 non-null  float64
 9   Total_Affected     14644 non-null  float64
 10  Damage_USD         14644 non-null  float64
 11  Magnitude          14644 non-null  float64
 12  Latitude           2331 non-null   object
 13  Longitude          2335 non-null   object
dtypes: float64(6), int64(1), object(7)
memory usage: 1.6+ MB

# Analytical Question 1

## How has the frequency of natural disasters changed over time across different disaster types?

### Objective
This analysis investigates how the number of recorded natural disasters has changed from 1970 to 2021. It also examines whether all disaster types have followed similar trends or if certain types have become more frequent over time.

### Why is this important?
Understanding long-term trends helps identify changes in global disaster patterns and supports disaster preparedness and climate adaptation planning.

In [12]:
import pandas as pd
import plotly.express as px

# Load dataset
df = pd.read_csv("../data/raw/emdat_disasters_1970_2021.csv")

print(df.shape)

(14644, 47)

In [13]:
# Keep only the required columns
q1_df = df[
    [
        "Year",
        "Disaster Type"
    ]
].copy()

q1_df.head()

   Year Disaster Type
0  1970         Flood
1  1970         Storm
2  1970         Flood
3  1970         Storm
4  1970         Storm

In [14]:
q1_df.isnull().sum()

Year             0
Disaster Type    0
dtype: int64

In [15]:
year_disaster = (
    q1_df
    .groupby(["Year", "Disaster Type"])
    .size()
    .reset_index(name="Disaster Count")
)

year_disaster.head()

   Year Disaster Type  Disaster Count
0  1970       Drought               2
1  1970    Earthquake              12
2  1970      Epidemic               4
3  1970         Flood              31
4  1970     Landslide               6

In [16]:
fig = px.line(
    year_disaster,
    x="Year",
    y="Disaster Count",
    color="Disaster Type",
    markers=True,
    title="Trend of Natural Disaster Types (1970–2021)",
    labels={
        "Year": "Year",
        "Disaster Count": "Number of Recorded Disasters",
        "Disaster Type": "Disaster Type"
    }
)

fig.update_layout(
    template="plotly_white",
    title={
        "text": "Trend of Natural Disaster Types (1970–2021)",
        "x": 0.5,
        "font": {"size": 22}
    },
    xaxis=dict(showgrid=False),
    yaxis=dict(showgrid=True, gridcolor="lightgray"),
    legend_title="Disaster Type",
    height=650,
    hovermode="x unified"
)

fig.show()

## Interpretation

The visualization shows how the frequency of different natural disaster types has evolved between 1970 and 2021. It highlights whether specific disaster categories have increased more rapidly than others and reveals long-term changes in global disaster occurrence. These trends provide evidence for changing disaster patterns over time and help identify which disaster types require greater attention in future disaster management strategies.

# Analytical Question 2

## Which disaster types have caused the highest total number of deaths globally?

### Objective

This analysis compares different disaster types based on the total number of fatalities they have caused worldwide.

### Why is this important?

Understanding which disaster types are the deadliest helps governments and disaster management agencies prioritize preparedness, mitigation strategies, and resource allocation.

In [17]:
# Select only required columns

q2_df = df[
    [
        "Disaster Type",
        "Total Deaths"
    ]
].copy()

q2_df.head()

  Disaster Type  Total Deaths
0         Flood          36.0
1         Storm          13.0
2         Flood           NaN
3         Storm      300000.0
4         Storm          17.0

In [18]:
q2_df.isnull().sum()

Disaster Type       0
Total Deaths     4445
dtype: int64

In [19]:
q2_df["Total Deaths"] = q2_df["Total Deaths"].fillna(0)

In [20]:
death_summary = (
    q2_df
    .groupby("Disaster Type", as_index=False)
    ["Total Deaths"]
    .sum()
    .sort_values(
        by="Total Deaths",
        ascending=False
    )
)

death_summary

            Disaster Type  Total Deaths
2              Earthquake     1319284.0
11                  Storm      817134.0
1                 Drought      700774.0
5                   Flood      330683.0
3                Epidemic      259735.0
4    Extreme temperature       189101.0
9               Landslide       40737.0
12      Volcanic activity       27135.0
13               Wildfire        2963.0
10    Mass movement (dry)        2324.0
6   Glacial lake outburst         250.0
0         Animal accident          12.0
8      Insect infestation           0.0
7                  Impact           0.0

In [21]:
fig = px.bar(
    death_summary,
    x="Total Deaths",
    y="Disaster Type",
    orientation="h",
    color="Total Deaths",
    text="Total Deaths",
    title="Earthquakes Have Caused the Highest Number of Recorded Deaths Worldwide"
)

fig.update_traces(
    texttemplate="%{text:,.0f}",
    textposition="outside"
)

fig.update_layout(
    template="plotly_white",
    title={
        "text":"Earthquakes Have Caused the Highest Number of Recorded Deaths Worldwide",
        "x":0.5,
        "font":{"size":22}
    },
    xaxis_title="Total Deaths",
    yaxis_title="Disaster Type",
    showlegend=False,
    xaxis=dict(showgrid=True, gridcolor="lightgray"),
    yaxis=dict(showgrid=False),
    height=650
)

fig.show()

## Interpretation

The chart compares disaster types based on their cumulative recorded fatalities. It highlights which hazards have had the greatest human impact over the study period. These findings help identify disaster categories that require stronger preparedness, early warning systems, and emergency response planning.

# Analytical Question 3

## How does the human impact of natural disasters vary across continents?

### Objective

This analysis compares the total number of people affected by natural disasters across different continents between 1970 and 2021.

### Why is this important?

While some continents experience more disasters than others, the number of people affected may differ significantly. Understanding regional human impact helps policymakers allocate disaster preparedness and humanitarian resources more effectively.

In [22]:
q3_df = df[
    [
        "Continent",
        "Total Affected"
    ]
].copy()

q3_df.head()

  Continent  Total Affected
0  Americas             NaN
1   Oceania             NaN
2    Africa             NaN
3      Asia       3648000.0
4      Asia           110.0

In [23]:
q3_df.isnull().sum()

Continent            0
Total Affected    3603
dtype: int64

In [24]:
q3_df["Total Affected"] = q3_df["Total Affected"].fillna(0)

In [25]:
continent_impact = (
    q3_df
    .groupby("Continent", as_index=False)
    ["Total Affected"]
    .sum()
    .sort_values(
        by="Total Affected",
        ascending=False
    )
)

continent_impact

  Continent  Total Affected
2      Asia    6.923120e+09
0    Africa    6.054536e+08
1  Americas    4.369688e+08
3    Europe    4.311441e+07
4   Oceania    2.631214e+07

In [26]:
fig = px.bar(
    continent_impact,
    x="Continent",
    y="Total Affected",
    color="Total Affected",
    text="Total Affected",
    title="Asia Has Experienced the Highest Human Impact from Natural Disasters"
)

fig.update_traces(
    texttemplate="%{text:,.0f}",
    textposition="outside"
)

fig.update_layout(
    template="plotly_white",
    title={
        "text":"Asia Has Experienced the Highest Human Impact from Natural Disasters",
        "x":0.5,
        "font":{"size":22}
    },
    xaxis_title="Continent",
    yaxis_title="Total People Affected",
    showlegend=False,
    xaxis=dict(showgrid=False),
    yaxis=dict(showgrid=True, gridcolor="lightgray"),
    height=650
)

fig.show()

## Interpretation

The visualization compares the cumulative number of people affected by natural disasters across continents. It highlights regional differences in disaster impact and identifies the areas that have experienced the greatest humanitarian burden over the study period. These insights can support disaster risk reduction and emergency planning at a regional level.

# Analytical Question 4

## Which countries have experienced the highest economic losses due to natural disasters?

### Objective

This analysis identifies the countries that have suffered the greatest cumulative economic damage from natural disasters between 1970 and 2021.

### Why is this important?

Economic losses influence recovery time, infrastructure planning, and disaster resilience. Comparing countries helps understand where disasters have imposed the greatest financial burden.

In [27]:
q4_df = df[
    [
        "Country",
        "Total Damages ('000 US$)"
    ]
].copy()

q4_df.head()

      Country  Total Damages ('000 US$)
0   Argentina                   25000.0
1   Australia                   72475.0
2       Benin                     200.0
3  Bangladesh                   86400.0
4  Bangladesh                       NaN

In [28]:
q4_df.isnull().sum()

Country                        0
Total Damages ('000 US$)    9781
dtype: int64

In [29]:
q4_df["Total Damages ('000 US$)"] = q4_df["Total Damages ('000 US$)"].fillna(0)

In [30]:
country_damage = (
    q4_df
    .groupby("Country", as_index=False)
    ["Total Damages ('000 US$)"]
    .sum()
)

country_damage = (
    country_damage
    .sort_values(
        by="Total Damages ('000 US$)",
        ascending=False
    )
    .head(15)
)

country_damage

,Country,Total Damages ('000 US$)
213,United States of America (the),1.223099e+09
40,China,6.105085e+08
98,Japan,5.298496e+08
89,India,1.419745e+08
96,Italy,9.569726e+07
158,Puerto Rico,7.265780e+07
9,Australia,6.391910e+07
72,Germany,5.788960e+07
126,Mexico,5.472252e+07
198,Thailand,5.258291e+07
66,France,4.587270e+07
39,Chile,3.866996e+07
212,United Kingdom of Great Britain and Northern I...,3.738468e+07
34,Canada,3.595210e+07
90,Indonesia,3.405971e+07

In [31]:
fig = px.bar(
    country_damage,
    x="Total Damages ('000 US$)",
    y="Country",
    orientation="h",
    color="Total Damages ('000 US$)",
    text="Total Damages ('000 US$)",
    title="Countries with the Highest Recorded Economic Losses from Natural Disasters"
)

fig.update_traces(
    texttemplate="%{text:,.0f}",
    textposition="outside"
)

fig.update_layout(
    template="plotly_white",
    title={
        "text":"Countries with the Highest Recorded Economic Losses from Natural Disasters",
        "x":0.5,
        "font":{"size":22}
    },
    xaxis_title="Total Economic Damage ('000 US$)",
    yaxis_title="Country",
    showlegend=False,
    xaxis=dict(showgrid=True, gridcolor="lightgray"),
    yaxis=dict(showgrid=False),
    height=700
)

fig.show()

## Interpretation

The visualization compares countries based on the total economic losses caused by natural disasters. It highlights which nations have experienced the greatest financial burden over the study period. The results provide insight into the economic vulnerability of different countries and can support investment in disaster resilience and infrastructure planning.

# Analytical Question 5

## Is there a relationship between disaster magnitude and the number of deaths?

### Objective

This analysis investigates whether disasters with higher recorded magnitudes generally result in more fatalities.

### Why is this important?

Understanding the relationship between disaster magnitude and fatalities helps evaluate disaster severity and supports improvements in early warning systems, emergency planning, and risk reduction strategies.

In [32]:
q5_df = df[
    [
        "Disaster Type",
        "Dis Mag Value",
        "Total Deaths"
    ]
].copy()

q5_df.head()

  Disaster Type  Dis Mag Value  Total Deaths
0         Flood            NaN          36.0
1         Storm            NaN          13.0
2         Flood            NaN           NaN
3         Storm            NaN      300000.0
4         Storm            NaN          17.0

In [33]:
q5_df.isnull().sum()

Disaster Type        0
Dis Mag Value    10075
Total Deaths      4445
dtype: int64

In [34]:
q5_df = q5_df.dropna(subset=["Dis Mag Value"])

q5_df["Total Deaths"] = q5_df["Total Deaths"].fillna(0)

q5_df.shape

(4569, 3)

In [35]:
fig = px.scatter(
    q5_df,
    x="Dis Mag Value",
    y="Total Deaths",
    color="Disaster Type",
    opacity=0.7,
    title="Relationship Between Disaster Magnitude and Fatalities",
    labels={
        "Dis Mag Value": "Disaster Magnitude",
        "Total Deaths": "Total Deaths"
    }
)

fig.update_layout(
    template="plotly_white",
    title={
        "text":"Relationship Between Disaster Magnitude and Fatalities",
        "x":0.5,
        "font":{"size":22}
    },
    xaxis=dict(showgrid=False),
    yaxis=dict(showgrid=True, gridcolor="lightgray"),
    height=700,
    legend_title="Disaster Type"
)

fig.update_yaxes(type="log")

fig.show()

## Interpretation

The scatter plot explores the relationship between disaster magnitude and the number of fatalities. While larger magnitude disasters often result in greater loss of life, the relationship is not perfectly linear. Some lower-magnitude events have caused significant fatalities due to factors such as population density, infrastructure quality, and preparedness. This indicates that disaster impact depends on both physical intensity and societal vulnerability.

# Analytical Question 6

## Do different disaster types occur more frequently during certain months of the year?

### Objective

This analysis investigates whether natural disasters exhibit seasonal patterns by comparing the monthly occurrence of different disaster types.

### Why is this important?

Identifying seasonal trends helps governments and emergency management agencies prepare resources and develop early warning systems before periods of increased disaster risk.

In [36]:
q6_df = df[
    [
        "Start Month",
        "Disaster Type"
    ]
].copy()

q6_df.head()

   Start Month Disaster Type
0          1.0         Flood
1          1.0         Storm
2          9.0         Flood
3         11.0         Storm
4          4.0         Storm

In [37]:
q6_df.isnull().sum()

Start Month      268
Disaster Type      0
dtype: int64

In [38]:
q6_df = q6_df.dropna(subset=["Start Month"])

q6_df["Start Month"] = q6_df["Start Month"].astype(int)

q6_df.shape

(14376, 2)

In [39]:
heatmap_data = (
    q6_df
    .groupby(["Disaster Type", "Start Month"])
    .size()
    .reset_index(name="Count")
)

heatmap_data = heatmap_data.pivot(
    index="Disaster Type",
    columns="Start Month",
    values="Count"
).fillna(0)

heatmap_data

Start Month,1,2,3,4,5,6,7,8,9,10,11,12
Disaster Type,,,,,,,,,,,,
Animal accident,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
Drought,114.0,30.0,47.0,50.0,46.0,56.0,51.0,37.0,30.0,37.0,23.0,33.0
Earthquake,90.0,90.0,97.0,101.0,107.0,82.0,94.0,91.0,96.0,96.0,98.0,95.0
Epidemic,352.0,92.0,97.0,77.0,87.0,90.0,89.0,103.0,90.0,118.0,89.0,104.0
Extreme temperature,140.0,38.0,6.0,15.0,29.0,52.0,116.0,27.0,3.0,11.0,35.0,108.0
Flood,393.0,312.0,353.0,383.0,448.0,568.0,616.0,668.0,426.0,413.0,337.0,323.0
Glacial lake outburst,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Impact,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Insect infestation,8.0,7.0,5.0,5.0,4.0,9.0,13.0,6.0,4.0,5.0,4.0,1.0
Landslide,69.0,63.0,58.0,62.0,56.0,60.0,84.0,62.0,54.0,43.0,40.0,49.0
Mass movement (dry),6.0,2.0,5.0,1.0,4.0,3.0,2.0,3.0,2.0,4.0,3.0,5.0
Storm,396.0,274.0,239.0,278.0,301.0,256.0,353.0,443.0,510.0,376.0,299.0,269.0
Volcanic activity,18.0,15.0,13.0,21.0,20.0,17.0,25.0,17.0,22.0,14.0,19.0,19.0
Wildfire,47.0,27.0,23.0,39.0,32.0,33.0,88.0,65.0,32.0,37.0,10.0,15.0

In [40]:
fig = px.imshow(
    heatmap_data,
    text_auto=True,
    aspect="auto",
    color_continuous_scale="Blues",
    title="Seasonal Patterns of Natural Disaster Types"
)

fig.update_layout(
    template="plotly_white",
    title={
        "text": "Seasonal Patterns of Natural Disaster Types",
        "x": 0.5,
        "font": {"size": 22}
    },
    xaxis_title="Month",
    yaxis_title="Disaster Type",
    height=700
)

fig.show()

## Interpretation

The heatmap reveals seasonal variations in the occurrence of different disaster types. Darker cells indicate months with higher frequencies of specific disasters, highlighting recurring seasonal patterns. These insights can support seasonal preparedness, resource allocation, and disaster risk management by identifying periods of elevated risk for particular hazards.

# Analytical Question 7

## Which disaster subgroups contribute the most to different disaster types?

### Objective

This analysis examines how disaster events are distributed across disaster subgroups and disaster types between 1970 and 2021.

### Why is this important?

Understanding the composition of disaster events provides a deeper understanding of global disaster patterns and highlights which subgroups dominate different categories of natural disasters.

In [41]:
q7_df = df[
    [
        "Disaster Subgroup",
        "Disaster Type"
    ]
].copy()

q7_df.head()

  Disaster Subgroup Disaster Type
0      Hydrological         Flood
1    Meteorological         Storm
2      Hydrological         Flood
3    Meteorological         Storm
4    Meteorological         Storm

In [42]:
q7_df.isnull().sum()

Disaster Subgroup    0
Disaster Type        0
dtype: int64

In [43]:
q7_df = q7_df.dropna()

q7_df.shape

(14644, 2)

In [44]:
treemap_data = (
    q7_df
    .groupby(
        ["Disaster Subgroup", "Disaster Type"]
    )
    .size()
    .reset_index(name="Number of Disasters")
)

treemap_data.head()

  Disaster Subgroup          Disaster Type  Number of Disasters
0        Biological        Animal accident                    1
1        Biological               Epidemic                 1436
2        Biological     Insect infestation                   93
3    Climatological                Drought                  685
4    Climatological  Glacial lake outburst                    2

In [45]:
fig = px.treemap(
    treemap_data,
    path=["Disaster Subgroup", "Disaster Type"],
    values="Number of Disasters",
    color="Number of Disasters",
    color_continuous_scale="Blues",
    title="Distribution of Natural Disaster Events by Subgroup and Type"
)

fig.update_layout(
    template="plotly_white",
    title={
        "text": "Distribution of Natural Disaster Events by Subgroup and Type",
        "x": 0.5,
        "font": {"size": 22}
    },
    height=750,
    margin=dict(t=60, l=20, r=20, b=20)
)

fig.show()

## Interpretation

The treemap illustrates the hierarchical distribution of disaster events across disaster subgroups and disaster types. Larger rectangles represent disaster categories with a higher number of recorded events. This visualization highlights which subgroups dominate global disaster occurrences and reveals the relative contribution of each disaster type within its subgroup.

# Analytical Question 8

## How do disaster types compare in terms of human impact and economic losses?

### Objective

This analysis compares disaster types based on the total number of people affected and the total economic losses they caused.

### Why is this important?

Some disaster types primarily affect people, while others result in greater financial losses. Comparing these impacts helps identify disaster types that require different response and mitigation strategies.

In [47]:
q8_df = df[
    [
        "Disaster Type",
        "Total Affected",
        "Total Damages ('000 US$)"
    ]
].copy()

q8_df.head()

  Disaster Type  Total Affected  Total Damages ('000 US$)
0         Flood             NaN                   25000.0
1         Storm             NaN                   72475.0
2         Flood             NaN                     200.0
3         Storm       3648000.0                   86400.0
4         Storm           110.0                       NaN

In [48]:
q8_df.isnull().sum()

Disaster Type                  0
Total Affected              3603
Total Damages ('000 US$)    9781
dtype: int64

In [49]:
q8_df["Total Affected"] = q8_df["Total Affected"].fillna(0)

q8_df["Total Damages ('000 US$)"] = (
    q8_df["Total Damages ('000 US$)"].fillna(0)
)

In [50]:
bubble_data = (
    q8_df
    .groupby("Disaster Type", as_index=False)
    .agg({
        "Total Affected": "sum",
        "Total Damages ('000 US$)": "sum"
    })
)

bubble_data

            Disaster Type  Total Affected  Total Damages ('000 US$)
0         Animal accident    5.000000e+00              0.000000e+00
1                 Drought    2.655003e+09              1.838986e+08
2              Earthquake    1.959006e+08              8.370863e+08
3                Epidemic    2.904026e+07              0.000000e+00
4    Extreme temperature     1.036355e+08              6.264634e+07
5                   Flood    3.818297e+09              9.067633e+08
6   Glacial lake outburst    2.400000e+01              2.100000e+05
7                  Impact    3.014910e+05              3.300000e+04
8      Insect infestation    2.802200e+06              2.301250e+05
9               Landslide    1.064828e+07              1.108891e+07
10    Mass movement (dry)    2.548700e+04              9.000000e+03
11                  Storm    1.192002e+09              1.640243e+09
12      Volcanic activity    9.374131e+06              5.069712e+06
13               Wildfire    1.793891e+07              1.200228e+08

In [51]:
fig = px.scatter(
    bubble_data,
    x="Total Affected",
    y="Total Damages ('000 US$)",
    size="Total Damages ('000 US$)",
    color="Disaster Type",
    hover_name="Disaster Type",
    size_max=60,
    title="Human Impact versus Economic Losses by Disaster Type",
    labels={
        "Total Affected": "Total People Affected",
        "Total Damages ('000 US$)": "Total Economic Damage ('000 US$)"
    }
)

fig.update_layout(
    template="plotly_white",
    title={
        "text": "Human Impact versus Economic Losses by Disaster Type",
        "x": 0.5,
        "font": {"size": 22}
    },
    xaxis=dict(showgrid=False),
    yaxis=dict(showgrid=True, gridcolor="lightgray"),
    height=700
)

fig.show()

## Interpretation

The bubble chart compares disaster types based on their cumulative human and economic impacts. Disaster types located in the upper-right corner have both high economic losses and a large number of affected people, while those positioned elsewhere indicate different impact profiles. This comparison highlights that disaster severity cannot be assessed using a single measure and that both humanitarian and economic consequences should be considered.

# Analytical Question 9

## Where are the global hotspots of recorded natural disasters?

### Objective

This analysis visualizes the geographic distribution of recorded natural disasters using their latitude and longitude coordinates.

### Why is this important?

Understanding the spatial distribution of disasters helps identify geographic hotspots, supports disaster risk assessment, and assists policymakers in prioritizing regions for preparedness and resilience planning.

In [53]:
q9_df = df[
    [
        "Latitude",
        "Longitude",
        "Disaster Type"
    ]
].copy()

q9_df.head()

  Latitude Longitude Disaster Type
0      NaN       NaN         Flood
1      NaN       NaN         Storm
2      NaN       NaN         Flood
3      NaN       NaN         Storm
4      NaN       NaN         Storm

In [54]:
q9_df.isnull().sum()

Latitude         12313
Longitude        12309
Disaster Type        0
dtype: int64

In [55]:
q9_df = q9_df.dropna(
    subset=[
        "Latitude",
        "Longitude"
    ]
)

q9_df.shape

(2329, 3)

In [56]:
q9_df["Latitude"] = pd.to_numeric(
    q9_df["Latitude"],
    errors="coerce"
)

q9_df["Longitude"] = pd.to_numeric(
    q9_df["Longitude"],
    errors="coerce"
)

q9_df = q9_df.dropna(
    subset=[
        "Latitude",
        "Longitude"
    ]
)

In [58]:
fig = px.scatter_geo(
    q9_df,
    lat="Latitude",
    lon="Longitude",
    color="Disaster Type",
    hover_name="Disaster Type",
    opacity=0.7,
    title="Global Distribution of Recorded Natural Disasters (1970–2021)"
)

fig.update_layout(
    template="plotly_white",
    title={
        "text": "Global Distribution of Recorded Natural Disasters (1970–2021)",
        "x": 0.5,
        "font": {"size": 22}
    },
    height=700,
    geo=dict(
        showland=True,
        landcolor="rgb(240,240,240)",
        showcountries=True,
        countrycolor="gray",
        showocean=True,
        oceancolor="lightblue"
    )
)

fig.show()

## Interpretation

The geographic map highlights the spatial distribution of recorded natural disasters worldwide between 1970 and 2021. Clusters of disaster events reveal regions with higher exposure to natural hazards. The visualization demonstrates that disaster occurrence is unevenly distributed across the globe, emphasizing the importance of location-specific disaster preparedness and risk management strategies.

# Analytical Question 10

## How are economic losses distributed across continents and disaster types?

### Objective

This analysis explores how the total economic losses from natural disasters are distributed across continents and disaster types.

### Why is this important?

Different continents experience different disaster profiles and economic consequences. Understanding these patterns helps policymakers prioritize investments in disaster resilience and infrastructure.

In [60]:
q10_df = df[
    [
        "Continent",
        "Disaster Type",
        "Total Damages ('000 US$)"
    ]
].copy()

q10_df.head()

  Continent Disaster Type  Total Damages ('000 US$)
0  Americas         Flood                   25000.0
1   Oceania         Storm                   72475.0
2    Africa         Flood                     200.0
3      Asia         Storm                   86400.0
4      Asia         Storm                       NaN

In [61]:
q10_df.isnull().sum()

Continent                      0
Disaster Type                  0
Total Damages ('000 US$)    9781
dtype: int64

In [62]:
q10_df = q10_df.dropna(
    subset=[
        "Continent",
        "Disaster Type"
    ]
)

q10_df["Total Damages ('000 US$)"] = (
    q10_df["Total Damages ('000 US$)"].fillna(0)
)

In [63]:
sunburst_data = (
    q10_df
    .groupby(
        ["Continent", "Disaster Type"],
        as_index=False
    )
    ["Total Damages ('000 US$)"]
    .sum()
)

sunburst_data.head()

  Continent         Disaster Type  Total Damages ('000 US$)
0    Africa       Animal accident                       0.0
1    Africa               Drought                 6377893.0
2    Africa            Earthquake                12675929.0
3    Africa              Epidemic                       0.0
4    Africa  Extreme temperature                    47809.0

In [64]:
fig = px.sunburst(
    sunburst_data,
    path=["Continent", "Disaster Type"],
    values="Total Damages ('000 US$)",
    color="Total Damages ('000 US$)",
    color_continuous_scale="Blues",
    title="Economic Losses by Continent and Disaster Type"
)

fig.update_layout(
    template="plotly_white",
    title={
        "text": "Economic Losses by Continent and Disaster Type",
        "x": 0.5,
        "font": {"size": 22}
    },
    height=750,
    margin=dict(t=60, l=20, r=20, b=20)
)

fig.show()



## Interpretation

The sunburst chart illustrates how economic losses are distributed across continents and disaster types. The size of each segment represents the cumulative financial impact, allowing comparisons between regions and disaster categories. The visualization reveals which combinations contribute the most to global disaster-related economic losses and highlights regional differences in disaster vulnerability.